### ISSUE TITLE
Very slow visalib.read() with instruments connected by USB

### ISSUE THREAD

**Issue by ayrodriguez** [hgrecco/pyvisa-py#48] opened 2015-07-06 15:37 UTC
The visalib.read() function takes about 6 seconds to return, whereas with usbtmc it's instantaneous.

pyvisa version 1.8.dev0
pyvisa-py version 0.2.dev2

**Comment by hgrecco** [comment] 2015-08-25 02:57
Sorry but I missed this, can you provide more info.

**Comment by herm** [comment] 2015-10-09 12:39
I'm having the same issue.
The problem is located here:
https://github.com/hgrecco/pyvisa-py/blob/master/pyvisa-py/usb.py#L98

USB communication never checks for the termination character but instead always uses the timeout.

**Comment by hgrecco** [comment] 2015-10-09 12:40
Please submit a PR, I will be happy to review it and merge it during the weekend.

**Comment by herm** [comment] 2015-10-09 12:51
I'm not sure how to fix it correctly. 
``lambda current: term_char_en and current.endswith(chr(term_char))`` 
works, but I think term_char_en should default to True for TMC but I don't know what the best place would be to set it.

**Comment by herm** [comment] 2015-10-27 14:59
This should be fixed now.

**Comment by hgrecco** [comment] 2015-10-27 15:00
@ayrodriguez Please confirm that this is fixed for you and close it! Thanks for the report and Thanks @herm  for the fix!

**Comment by hgrecco** [comment] 2016-08-22 15:19
I am closing this for now. Feel free to reopen or open another if necessary.

**Closed by hgrecco** 2016-08-22 15:19 UTC
